### PR TITLE
Use Node.contains instead

### PR DESCRIPTION
**Pull request by fregante**
Supported in IE5+ https://developer.mozilla.org/en-US/docs/Web/API/Node/contains

### CODE REVIEW

**Comment by matthewmueller** [comment]
not 100% sure, but i don't think this is quite right. i think it should be:

``` js
return parent == child || parent.contains(child)
```

in general, :+1: to this change though.

**Comment by fregante** [comment]
Not necessary :)
`document.body.contains(document.body) === true`

**Comment by matthewmueller** [comment]
sweet :-D thanks for proving that out.

**Comment by fregante** [comment]
Glad to be of help! I started publishing my micro DOM modules so I found all your little modules while I was looking for duplicates. Sure enough there were a few already in `npm-dom` :)

**Pull request merged**
